server:
  port: 4648
logging:
  level:
    design.lanmu.mapper: DEBUG

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/personnel
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql